In [1]:
import numpy as np
import pandas as pd 
import statsmodels.api as sm
import statsmodels.formula.api as smf
import seaborn as sns
from sklearn.preprocessing import scale 
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import roc_auc_score,roc_curve
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

from warnings import filterwarnings
filterwarnings('ignore')

## Gaussian Naive Bayes - Classification Problems

In [8]:
diabetes=pd.read_csv("diabetes.csv")
df=diabetes.copy()
y=df["Outcome"]
X=df.drop(["Outcome"], axis=1)
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.30, random_state=42)


In [14]:
nb=GaussianNB()

nb_model=nb.fit(x_train,y_train)
nb_model


GaussianNB()

In [17]:
y_pred=nb_model.predict(x_test)[0:10]
y_pred


array([0, 0, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int64)

In [21]:
#if we want to see the proba values.

nb_model.predict_proba(x_test)[0:10]

array([[0.73815858, 0.26184142],
       [0.94027894, 0.05972106],
       [0.97242831, 0.02757169],
       [0.82840069, 0.17159931],
       [0.47153473, 0.52846527],
       [0.47274458, 0.52725542],
       [0.99607705, 0.00392295],
       [0.69925055, 0.30074945],
       [0.53838117, 0.46161883],
       [0.25004536, 0.74995464]])

In [22]:
y_pred= nb_model.predict(x_test)

accuracy_score(y_test,y_pred)

0.7445887445887446

In [23]:
#model_tuning

cross_val_score(nb_model, x_test,y_test, cv=10)

array([0.75      , 0.7826087 , 0.82608696, 0.82608696, 0.91304348,
       0.7826087 , 0.86956522, 0.60869565, 0.69565217, 0.69565217])

In [24]:
cross_val_score(nb_model, x_test,y_test, cv=10).mean()

0.775